sudo: required
language: cpp
services:
  - docker
before_install:
  - docker --version
#  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
#  - docker pull ${DOCKER_HUB_REPO}
#  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
#  - docker build -t ${DOCKER_HUB_REPO}:${TRAVIS_COMMIT} .
   - docker build -t plstcharles/litiv-base .
script:
#  - docker run ...
  - echo 'todo, add testing!'
after_success:
#  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag ${DOCKER_HUB_REPO}:${TRAVIS_COMMIT} ${DOCKER_HUB_REPO}:${TRAVIS_TAG}; fi
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker push plstcharles/litiv-base